### ISSUE TITLE
Directory structure to save Curriculum to disk

### ISSUE THREAD

**Issue by lichtefeld** [isi-vista/adam#1027]
To facilitate an easy transfer of curriculum & perceptual processing from ASU -> ADAM a standardized directory structure will be useful. To start this discussion I've outlined an initial layout below. @blakeharrison-ai @shengcheng @denizbeser Please comment any feedback, concerns, etc on this issue. If you don't have any concerns at least let me know that the outline is sufficient that way its clear we'll be working towards the established format here for all development. 

The basis for this layout assumes that each curriculum set is its own directory. A curriculum should also be able to be defined as a collection of sub-curriculum units (e.g. a complete curriculum includes teaching objects then teaching actions, each of which is a separate directory).

### Curriculum Directory Structure
```
- info.yaml
- situation_1
  - scene_1.png
  - description.yaml
  - scene_1_point_cloud.file # See questions
- situation_2
  - etc.
- situation_N
```

### info.yaml
```yaml
curriculum_type: "situation" # "curriculum" indicating a collection of curriculum.
num_dirs: N # This is either the number of situations or sub-curriculums in the curriculum.
created_on: "2021-09-13T19:10:23Z" # ISO formatted date & time of creation 
```

### description.yaml
This yaml file should contain the linguistic pair for the situation along with the "gold standard" object information about which objects are present in the scene and their rough location in the 2D image. This way when in the UI we can provide some contextual "goal standard" information for comparison with the learned results or to do some automatic metric generation. 

```yaml
language: "roll ball"
gold_objects_in_scene:
  - ball:
    - location: (X1,Y1) (X2,Y2)
    - color bin: "red"
    - etc
  - person:
    - ...
  - table:
    - ...
  - ...
```

We can break the language and gold standard information out into two files for clarity that we aren't cheating if that is helpful. That may be the best route to go.

### Questions
Do we want to save the point-cloud representation to disk? We don't need saved to disk as far as I'm concerned but for completeness it may make sense to include this here.
