### ISSUE TITLE
Implement a simple curriculum generator

### ISSUE THREAD

**Issue by denizbeser** [isi-vista/adam#1035]
This is the step 1 in #1032. This is a generator that should generate pairs of language and images to be displayed.

**Comment by lichtefeld** [comment]
@blakeharrison-ai You had discussed having a template like file here which could be used to indicate required objects and constraints while the rest of the scene is handled via procedural generation. 

Personally I'm in favor of these template files as I think that will make it easier for @denizbeser and myself to draft situations to turn into a complex curriculum in a consistent manner with you.

**Comment by lichtefeld** [comment]
@blakeharrison-ai -- I should be able to somewhat easily implement a high-level representation of a situation in the following YAML format. I've gone ahead an indicated a potential inclusion of spatial relationships and actions but those aren't needed for the MVP implementation.

### Simple Scene describing a ball out of 3 objects total.
```yaml
num_scenes_to_generate: 5
language: ball
objects:
  - type: ball
    properties:
      - color: red
      - material: rubber
    id: 0
  - type: any
    id: 1
  - type: any
    id: 2
```

### Complex scene with actions
```yaml
num_scenes_to_generate: 5
language: throw ball in box
objects:
  - type: ball
    properties:
      - color: red
      - material: rubber
    id: 0
  - type: person
    id: 1
  - type: box
    id: 2
before_relations:
  - distance: contact
    object_0: 0
    object_1: 1
  - distance: distal
    object_0: 1
    object_1: 2
after_relations:
  - distance: inside
    object_0: 0
    object_1: 2
actions:
  - type: throw
    alignments:
      - agent: 0
      - patient: 1
      - theme: 2
```

Thoughts, comments, concerns?
