### ISSUE TITLE
Visual Processing Features file format updates

### ISSUE THREAD

**Issue by lichtefeld** [isi-vista/adam#1077]
When reviewing M4 feature files I noticed some places where improvements could be made for future output (and a regeneration of the curriculum). 

- [x] `strokes_normalized_corrdinates` is a typo it should be `strokes_normalized_coordinates`
- [x] split `stroke_mean_std` into three distinct values: `stroke_mean_x`, `stroke_mean_y` and `stroke_std` -- These values being nested into a list makes the code to extract the values harder to understand. It would be clearer if each of these values were a key lookup. An example of the new version is provided below 
```yaml
    stroke_mean_x: 117.72496130949432
    stroke_mean_y: 76.65807840610996
    stroke_std: 26.746551756764745
```
- [x] Organize objects into a list rather than making objects a key lookup by object name. As the collection of objects detected in the scene could be of variable length it is cleaner to instantiate these objects via a loop. As such, being able to iterate over entries into a list would be clearer to read and match the intent of a variable number of objects better.

@shengcheng What is the turn around time for implementing these changes requested above? I can take care of converting the M4 curriculum's into a format with these changes.

**Comment by lichtefeld** [comment]
From the team meeting on 12/13 we decided to move forward with using the Stroke GNN for object recognition when our curriculum is essentially labeled training data. We'll revisit an approach at merging different approaches together for handling a more complex training scene in the future.

This means that a) we want to include a `concept_name` field in the dict for objects which is the resulting category from the Stroke GNN. We'll identify this as the alignment information for ADAM to display in the UI.

**Comment by lichtefeld** [comment]
We also want to introduce distances (and axes) into this format. For the axes lengths of objects I propose the following. This is a subset of the YAML file for features including the new keys for the distances.
```yaml
objects:
- object_name: object0
   confidence_score: 1.0
   axes: # 3 axes aligned to x, y, z (or i, j, k)
      - distance: 123.45 # Value in cm and a float
        axes_alignment: x
        direction: None # Select from: None (n/a), True (positive), False, (negative) values.
spatial_relations:
- source: object0 # Links to an `object_name` field
   destination: object1 # Links to an `object_name` field
   axes: # 3 axes aligned to x, y, z (or i, j, k)
      - distance: 123.45 # Value in cm and a float
        axes_alignment: x
        direction: True # Select from: None (n/a), True (positive), False, (negative) values.
```

@blakeharrison-ai Please let me know if this doesn't seem reasonable for a file format output.
